//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.AdminStore.WebForm.Catalog {
    
    
    public partial class custom_dict_default {
        
        /// <summary>
        /// enbNotice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Apollo.AdminStore.WebForm.UserControls.NoticeBoxControl enbNotice;
        
        /// <summary>
        /// lbPublish control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbPublish;
        
        /// <summary>
        /// gvItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Apollo.AdminStore.WebForm.Classes.CustomGrid gvItems;
    }
}
